# Course Name: Data Science Tools & Techniques Course Code: AM609
# Name : Chetan Sethy , Data Science
# Regd Num : 24-22-27

### Q1
a) Create a variable named var1 that stores an array of numbers from 0 to 30,
inclusive. Print var1 and its shape. Hint : arange

In [178]:
import numpy as np
var1 = np.arange(0,31)
print("var1:", var1)
print("Shape of var1:", var1.shape)

var1: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30]
Shape of var1: (31,)


### 
b) Change var2 to a validly-shaped two-dimensional matrix and store it in a
new variable called var2. Print var2 and its shape. Hint: Use the reshape function

In [181]:
var2 = var1[:30].reshape(5, 6)
print(var2)
print("Shape of var2:", var2.shape)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
Shape of var2: (5, 6)


c) Create a third variable, var3 that reshapes it into a valid three-dimensional shape.
Print var3 and its shape

In [184]:
var3 = var1.reshape(31,1,1)
print(var3)
print("Shape of var3:", var3.shape)

[[[ 0]]

 [[ 1]]

 [[ 2]]

 [[ 3]]

 [[ 4]]

 [[ 5]]

 [[ 6]]

 [[ 7]]

 [[ 8]]

 [[ 9]]

 [[10]]

 [[11]]

 [[12]]

 [[13]]

 [[14]]

 [[15]]

 [[16]]

 [[17]]

 [[18]]

 [[19]]

 [[20]]

 [[21]]

 [[22]]

 [[23]]

 [[24]]

 [[25]]

 [[26]]

 [[27]]

 [[28]]

 [[29]]

 [[30]]]
Shape of var3: (31, 1, 1)


In [186]:
var2[1, 0] = -1

var3 = var1.reshape(31, 1, 1)

print("var2 after modification:\n", var2)
print("var1 after modifying var2:\n", var1)
print("var3 after modifying var2:\n", var3)


var2 after modification:
 [[ 0  1  2  3  4  5]
 [-1  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
var1 after modifying var2:
 [ 0  1  2  3  4  5 -1  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30]
var3 after modifying var2:
 [[[ 0]]

 [[ 1]]

 [[ 2]]

 [[ 3]]

 [[ 4]]

 [[ 5]]

 [[-1]]

 [[ 7]]

 [[ 8]]

 [[ 9]]

 [[10]]

 [[11]]

 [[12]]

 [[13]]

 [[14]]

 [[15]]

 [[16]]

 [[17]]

 [[18]]

 [[19]]

 [[20]]

 [[21]]

 [[22]]

 [[23]]

 [[24]]

 [[25]]

 [[26]]

 [[27]]

 [[28]]

 [[29]]

 [[30]]]


### e)
Another thing that comes up a lot with array shapes is thinking about how to
aggregate over specific dimensions. Figure out how the NumPy sum function
works (and the axis argument in particular) and do the following:
(i) Sum var3 over its second dimension and print the result.
(ii) Sum var3 over its third dimension and print the result.
(iii) Sum var3 over both its first and third dimensions and print the result.

In [189]:
# (i) Sum var3 over its second dimension (axis 1)
sum_over_second_dim = np.sum(var3, axis=1)
print("Sum over second dimension (axis 1):", sum_over_second_dim)

Sum over second dimension (axis 1): [[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [-1]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]
 [24]
 [25]
 [26]
 [27]
 [28]
 [29]
 [30]]


In [191]:
# (ii) Sum var3 over its third dimension (axis 2)
sum_over_third_dim = np.sum(var3, axis=2)
print("Sum over third dimension (axis 2):", sum_over_third_dim)

Sum over third dimension (axis 2): [[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [-1]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]
 [24]
 [25]
 [26]
 [27]
 [28]
 [29]
 [30]]


In [193]:
# (iii) Sum var3 over both its first and third dimensions (axes 0 and 2)
sum_over_first_third_dim = np.sum(var3, axis=(0, 2))
print("Sum over first and third dimensions (axes 0 and 2):", sum_over_first_third_dim)

Sum over first and third dimensions (axes 0 and 2): [458]


In [195]:
# (i)  Slice out the second row (index 1)
second_row = var2[1, :]
print("Second row of var2:", second_row)


Second row of var2: [-1  7  8  9 10 11]


In [197]:
# (ii) Slice out the last column (all rows, last column)
last_column = var2[:, -1]
print("Last column of var2:", last_column)


Last column of var2: [ 5 11 17 23 29]


In [199]:
# (iii) Slice out the top-right 2x2 submatrix (first two rows, last two columns)
top_right_submatrix = var2[:2, -2:]
print("Top-right 2x2 submatrix of var2:\n", top_right_submatrix)


Top-right 2x2 submatrix of var2:
 [[ 4  5]
 [10 11]]


### Q2 a) 
The most basic kind of broadcast is with a scalar, in which you can perform a
binary operation (e.g., add, multiply, ...) on an array and a scalar, the effect is to
perform that operation with the scalar for every element of the array. To try this
out, create a vector 1, 2, . . . , 10 by adding 1 to the result of the arange function.

In [203]:
vector = np.arange(10) + 1
print("Vector from 1 to 10:", vector)


Vector from 1 to 10: [ 1  2  3  4  5  6  7  8  9 10]


### b) 
Now, create a 10 × 10 matrix A in which Ai j = i + j. You’ll be able to do this
using the vector you just created, and adding it to a reshaped version of itself.

In [206]:
# Create the 10x10 matrix A where A[i, j] = i + j
A = vector.reshape(10, 1) + vector

# Print the matrix A
print("Matrix A (10x10) where A[i, j] = i + j:\n", A)


Matrix A (10x10) where A[i, j] = i + j:
 [[ 2  3  4  5  6  7  8  9 10 11]
 [ 3  4  5  6  7  8  9 10 11 12]
 [ 4  5  6  7  8  9 10 11 12 13]
 [ 5  6  7  8  9 10 11 12 13 14]
 [ 6  7  8  9 10 11 12 13 14 15]
 [ 7  8  9 10 11 12 13 14 15 16]
 [ 8  9 10 11 12 13 14 15 16 17]
 [ 9 10 11 12 13 14 15 16 17 18]
 [10 11 12 13 14 15 16 17 18 19]
 [11 12 13 14 15 16 17 18 19 20]]


### c)
A very common use of broadcasting is to standardize data, i.e., to make it have
zero mean and unit variance. First, create a fake “data set” with 50 examples,
each with five dimension
s  Hint "" .
import numpy.random as npr
data = np.exp(npr.randn ( 50 , 5 "" ) )

In [209]:
import numpy as np
import numpy.random as npr

# Create a fake dataset with 50 examples and 5 dimensions
data = np.exp(npr.randn(50, 5))

# Print the first few rows of the dataset to see what it looks like
print("Fake dataset (first 5 rows):\n", data[:5])


Fake dataset (first 5 rows):
 [[0.47508467 1.00672429 0.63847938 0.08679523 0.61283838]
 [0.47516572 3.86820108 0.94887374 0.85939818 1.38663497]
 [1.30037628 0.69270063 1.90554494 0.30789515 0.75621622]
 [1.34521237 2.00051458 0.17421354 0.10738262 9.72923846]
 [1.19069818 0.68324476 1.12454313 0.19420519 3.96849757]]


### d,e,f)


In [212]:
# Compute the mean of each column
mean_vector = data.mean(axis=0)

# Compute the standard deviation of each column
std_vector = data.std(axis=0)

# Print the mean and standard deviation vectors
print("Mean of each column:", mean_vector)
print("Standard deviation of each column:", std_vector)




#f) 
# Standardize the data matrix
normalized = (data - mean_vector) / std_vector

# Print the first 5 rows of the normalized matrix
print("Normalized data (first 5 rows):\n", normalized[:5])

# Verify the result by computing the mean and standard deviation of the normalized data
normalized_mean = normalized.mean(axis=0)
normalized_std = normalized.std(axis=0)

# Print the mean and standard deviation of the normalized data
print("Mean of normalized data (should be close to 0):", normalized_mean)
print("Standard deviation of normalized data (should be close to 1):", normalized_std)


Mean of each column: [2.05688326 1.56047106 1.40145112 2.02387439 1.70503427]
Standard deviation of each column: [2.57036673 1.6667864  1.23769291 2.56893324 1.72913151]
Normalized data (first 5 rows):
 [[-0.61539801 -0.3322242  -0.61644672 -0.75404029 -0.6316442 ]
 [-0.61536648  1.38453855 -0.36566209 -0.45329174 -0.18413828]
 [-0.29431869 -0.52062486  0.40728505 -0.66797347 -0.54872521]
 [-0.27687523  0.26400714 -0.99155256 -0.7460263   4.64059798]
 [-0.33698891 -0.52629797 -0.22372915 -0.71222917  1.30901744]]
Mean of normalized data (should be close to 0): [ 8.21565038e-17  2.42583731e-16 -2.88657986e-17 -3.38618023e-17
  2.37587727e-16]
Standard deviation of normalized data (should be close to 1): [1. 1. 1. 1. 1.]


# Q3

In [215]:
import numpy as np

def Vandermonde(N):
    base = np.arange(N, dtype=np.int64) + 1  # Create base array [1, 2, ..., N]
    power = np.arange(N, dtype=np.int64)     # Create power array [0, 1, 2, ..., N-1]
    base = base.reshape(N, 1)                # Reshape base to (N, 1)
    
    vander = base ** power                   # Create Vandermonde matrix
    
    return vander                            # Return the matrix

# Create Vandermonde matrix for N = 12
vander_matrix = Vandermonde(12)
print(vander_matrix)

# Create a vector of ones of length 12
x = np.ones(12, dtype=np.int64)  # Using int64 for consistency
print(x)

# Perform matrix-vector multiplication
b = vander_matrix @ x  # or you can use np.dot(vander_matrix, x)

# Print the resulting vector b
print("Vector b (result of matrix-vector multiplication):\n", b)

import numpy.linalg as linalg

# Solve for x by inverting the Vandermonde matrix and multiplying by b
# x_solved = linalg.inv(vander_matrix) @ b
x_solved = linalg.solve(vander_matrix, b)

# Print out the result
print("Solved vector x:\n", x_solved)


[[           1            1            1            1            1
             1            1            1            1            1
             1            1]
 [           1            2            4            8           16
            32           64          128          256          512
          1024         2048]
 [           1            3            9           27           81
           243          729         2187         6561        19683
         59049       177147]
 [           1            4           16           64          256
          1024         4096        16384        65536       262144
       1048576      4194304]
 [           1            5           25          125          625
          3125        15625        78125       390625      1953125
       9765625     48828125]
 [           1            6           36          216         1296
          7776        46656       279936      1679616     10077696
      60466176    362797056]
 [           1        

# https://github.com/chetan7659/DSTT_Assignment.git